url: https://sectordefectuoso.com
title: Sector Defectuoso
subtitle: "0 bytes en sectores defectuosos"
description: ""
lang: es

layout: default
comments: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: /pagina/:num/
disqus:
  shortname: sectordefectuoso

google_analytics: UA-130344597-1

archive_page: /archivo/
category_page: /categorias/
tag_page: /etiquetas/

collections:
  microblog:
    output: true
    permalink: microblog/:year/:month/:day/:hour-:minute-:second/
